// Code generated by sqlc. DO NOT EDIT.
// source: books.sql

package db

import (
	"context"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (
  title
) VALUES (
  $1
) RETURNING id, title, created_at, updated_at
`

func (q *Queries) CreateBook(ctx context.Context, title string) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook, title)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
